In [1]:
list = [1, 2, 3]
print(list)

[1, 2, 3]


In [2]:
tuple = (1, 2, 3)
print(tuple)

(1, 2, 3)


In [3]:
dic = {'key1' : 10, 'key2' : 20}
print(dic)

{'key1': 10, 'key2': 20}


In [9]:
import numpy as np

x = np.arange(12)
print(x)
x = x.reshape(4,3)
print(x)
print(x.shape)
print(x.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
12


In [10]:
x[:, 1:]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [11]:
x[:, ::2] #start:end:step

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [13]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [14]:
np.matmul(a,b)

array([[10, 13],
       [28, 40]])

In [15]:
a = np.arange(120).reshape(2,3,4,5) # (4행 5열인 배열이 3개)가 2개
print(a)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [18]:
print(a[:,:,:,0])
print(a[:,:,:,0].shape)

[[[  0   5  10  15]
  [ 20  25  30  35]
  [ 40  45  50  55]]

 [[ 60  65  70  75]
  [ 80  85  90  95]
  [100 105 110 115]]]
(2, 3, 4)
